[package]
name = "blog"
version = "0.1.0"
edition="2021"

[dependencies]
rocket_contrib = "0.4.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
jsonwebtoken = "7.0.0"
chrono = "0.4"
strsim="0.10.0"

[dependencies.rocket]
version = "0.5.0"
features = ["json"]